name: Ejemplo GitHub Actions
on: 
    workflow_dispatch:
    # schedule:
    # - cron: '*/5 * * * *' # Cada 5 minutos
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - '.github/workflows/main.yml'    
    pull_request:
        branches:
            - main
        paths:
            - 'src/**'
            - '.github/workflows/main.yml'
jobs:
    saludar:
        runs-on: ubuntu-latest
        steps:
            - name: Muestra mensaje Hola Mundo
              run: echo "Hola Mundo con GitHub Actions"
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Listar archivos del repositorio
              run: |
                  echo "El repositorio ${{github.repositorio}} contiene los siguientes archivos"
                  tree
